@ECHO OFF
:trojan
echo SENDING VIRUS...
pause
echo ATTENZIONE: IL SISTEMA E STATO CONTAMINATO DA UN VIRUS LETALE, (C:) VERRA FORMATTATO.
pause
cls
echo AHAHAHAHAHAAHA CI SEI CASCATO?CERTO CHE SEI INTELLIGENTE...
pause
echo DAVVERO CREDEVI CHE CI FOSSE UN VIRUS?
pause
echo MA SI PUO ESSERE COSI SCEMI??? XDXDXD
pause
MD EHEH
MD UHAUAHAUAH
MD MUAHAHAHA
MD EHAHUH
MD IHIHIHIHI
MD UHAUAHAUEH
MD OHAIAHAIO
MD AHAHAHAHAAH
MD DOHHHH
@ECHO OFF
echo PREMERE UN TASTO PER CANCELLARE AUTOMATICAMENTE LE DIRECTORY.
pause
echo CI SEI CASCATO ANCORA!!!NON CI CREDO...MA ALLORA SEI SCEMO!
MD SCEMOO
MD SCEEMOO
MD SCEEEMOO
MD Documentii
MD EHEHE
MD UHAUAHAUAHU
MD MUAHAHAHAA
MD EHAHUHE
MD IHIHIHIHII
MD UHAUAHAUEHU
MD OHAIAHAIOO
MD AHAHAHAHAAHA
MD DOHHHHH
pause
echo E CON QUESTA TI SALUTO!ALLA PROSSIMAAAAAA!!!
pause
echo CIAO CIAOOOOO!
pause
cls
echo VIRUS ALERT!THE SYSTEM SHUTTING DOWN : 1 MINUTS...
start shutdown -s -t 60 -c "TI HO FREGATO!!!POLLO!!!"
pause
echo PREMERE TASTO A CASO PER DISATTIVARE LO SPEGNIMENTO DEL PC"
shutdown -a
pause
RENAME ridere.bat FREGATO!.bat